services:
  - type: web
    name: seiji-backend
    env: docker
    plan: free
    repo: https://github.com/KENKUN-1031/seiji-backend
    branch: develop
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
envVars:
  - key: GIN_MODE
    value: release
